name: hacki
description: A Hacker News reader.
version: 1.6.0+110
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.0"

dependencies:
  adaptive_theme: ^3.2.0
  badges: ^3.0.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  clipboard: ^0.1.3
  collection: ^1.17.0
  connectivity_plus: ^3.0.2
  device_info_plus: ^8.1.0
  dio: ^5.0.3
  equatable: ^2.0.5
  fast_gbk: ^1.0.0
  feature_discovery:
    git:
      url: https://github.com/livinglist/feature_discovery
      ref: flutter3_compatibility
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.0
  flutter_email_sender: ^5.2.0
  flutter_fadein: ^2.0.0
  flutter_feather_icons: 2.0.0+1
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^13.0.0
  flutter_secure_storage: ^8.0.0
  flutter_siri_suggestions: ^2.1.0
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.3.0
  gbk_codec: ^0.4.0
  get_it: ^7.2.0
  hive: ^2.2.3
  html: ^0.15.1
  html_unescape: ^2.0.0
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  in_app_review:
    path: components/in_app_review
  intl: ^0.18.0
  linkify: ^4.1.0
  logger: ^1.3.0
  memoize: ^3.0.0
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.12
  path_provider_android: ^2.0.22
  path_provider_foundation: ^2.1.1
  pull_to_refresh:
    git:
      url: https://github.com/livinglist/flutter_pulltorefresh
      ref: master
  receive_sharing_intent: ^1.4.5
  responsive_builder: ^0.5.1
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.5
  sembast: ^3.4.0+6
  share_plus: ^6.3.1
  shared_preferences: ^2.0.17
  shared_preferences_android: ^2.0.15
  shared_preferences_foundation: ^2.1.3
  shimmer: ^2.0.0
  synced_shared_preferences:
    path: components/synced_shared_preferences
  tuple: ^2.0.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.9
  wakelock: ^0.6.1+2
  webview_flutter: ^4.0.2
  workmanager: ^0.5.1

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/roboto_slab/RobotoSlab-Regular.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Regular.ttf
        - asset: assets/fonts/ubuntu_mono/UbuntuMono-Bold.ttf
          weight: 700
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/noto_serif/NotoSerif-Regular.ttf
        - asset: assets/fonts/noto_serif/NotoSerif-Bold.ttf
          weight: 700


