name: hacki
description: A Hacker News reader.
version: 0.2.0+28
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  badges: ^2.0.2
  bloc: ^7.0.0
  cached_network_image: ^3.2.0
  clipboard: ^0.1.3
  collection:
  dio: ^4.0.4
  equatable: 2.0.3
  fast_gbk: ^1.0.0
  feature_discovery: ^0.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_fadein: ^2.0.0
  flutter_feather_icons: 2.0.0+1
  flutter_html: ^2.2.1
  flutter_inappwebview: ^5.3.2
  flutter_linkify: ^5.0.2
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.2.0
  font_awesome_flutter: ^9.2.0
  gbk_codec: ^0.4.0
  get_it: 7.2.0
  hive: ^2.0.6
  html: ^0.15.0
  html_unescape: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.8
  pull_to_refresh: ^2.0.0
  sembast: ^3.1.1+1
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  tuple: ^2.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.10

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/hacki_icon.png
    - images/hacker_news_logo.png


